# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  proxy:
    image: traefik:v3.2.5
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: .
    env_file:
      - .env
    labels:
      traefik.http.routers.backend.rule: "Host(`localhost`) && PathPrefix(`/prod-api`)"
      traefik.http.services.backend.loadbalancer.server.port: 8000

  frontend:
    image: ruoyi-vue3:latest
    labels:
      traefik.http.routers.frontend.rule: "Host(`localhost`)"
      traefik.http.services.frontend.loadbalancer.server.port: 3000
